from __future__ import annotations

from datetime import datetime

from sqlalchemy import DateTime, Enum, Float, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base
from app.models.enums import SensorStatus, ShipmentStatus, StorageBookingStatus
from app.models.mixins import TimestampMixin


class Shipment(Base, TimestampMixin):
    __tablename__ = "shipments"

    id: Mapped[int] = mapped_column(primary_key=True)
    lot_id: Mapped[int] = mapped_column(ForeignKey("lots.id"), nullable=False)
    purchase_order_id: Mapped[int] = mapped_column(
        ForeignKey("purchase_orders.id"), nullable=False
    )
    transporter_id: Mapped[int] = mapped_column(
        ForeignKey("transporter_profiles.id"), nullable=False
    )

    vehicle_number: Mapped[str] = mapped_column(String(20), nullable=False)
    vehicle_type: Mapped[str] = mapped_column(String(60), nullable=False)
    capacity_kg: Mapped[float] = mapped_column(Float, nullable=False)
    driver_contact: Mapped[str] = mapped_column(String(20), nullable=False)
    pickup_point: Mapped[str] = mapped_column(String(255), nullable=False)
    delivery_point: Mapped[str] = mapped_column(String(255), nullable=False)
    estimated_cost: Mapped[float] = mapped_column(Float, default=0.0)

    pickup_scheduled_at: Mapped[datetime | None] = mapped_column(
        DateTime, nullable=True
    )
    picked_up_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    delivered_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    status: Mapped[ShipmentStatus] = mapped_column(
        Enum(ShipmentStatus), default=ShipmentStatus.ASSIGNED
    )

    lot: Mapped["Lot"] = relationship()  # noqa: F821
    transporter: Mapped["TransporterProfile"] = relationship()  # noqa: F821
    purchase_order: Mapped["PurchaseOrder"] = relationship()  # noqa: F821


class StorageBooking(Base, TimestampMixin):
    __tablename__ = "storage_bookings"

    id: Mapped[int] = mapped_column(primary_key=True)
    lot_id: Mapped[int] = mapped_column(ForeignKey("lots.id"), nullable=False)
    facility_id: Mapped[int] = mapped_column(
        ForeignKey("storage_facilities.id"), nullable=False
    )
    booked_quantity_kg: Mapped[float] = mapped_column(Float, nullable=False)
    start_date: Mapped[str] = mapped_column(String(20), nullable=False)
    end_date: Mapped[str | None] = mapped_column(String(20), nullable=True)
    status: Mapped[StorageBookingStatus] = mapped_column(
        Enum(StorageBookingStatus), default=StorageBookingStatus.BOOKED
    )

    facility: Mapped["StorageFacility"] = relationship()  # noqa: F821


class StorageEvent(Base):
    """A simulated IoT sensor reading for a storage facility.

    Readings are generated by app/services/iot_simulator.py for demo
    purposes. This does not certify shelf life or food safety.
    """

    __tablename__ = "storage_events"

    id: Mapped[int] = mapped_column(primary_key=True)
    facility_id: Mapped[int] = mapped_column(
        ForeignKey("storage_facilities.id"), nullable=False
    )
    booking_id: Mapped[int | None] = mapped_column(
        ForeignKey("storage_bookings.id"), nullable=True
    )
    temperature_celsius: Mapped[float] = mapped_column(Float, nullable=False)
    humidity_percent: Mapped[float] = mapped_column(Float, nullable=False)
    occupancy_percent: Mapped[float] = mapped_column(Float, nullable=False)
    status: Mapped[SensorStatus] = mapped_column(
        Enum(SensorStatus), default=SensorStatus.NORMAL
    )
    recorded_at: Mapped[datetime] = mapped_column(DateTime, index=True)
